BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[Evaluation] (
    [id] INT NOT NULL IDENTITY(1,1),
    [createdAt] DATETIME2 NOT NULL CONSTRAINT [Evaluation_createdAt_df] DEFAULT CURRENT_TIMESTAMP,
    [clientName] NVARCHAR(1000) NOT NULL,
    [supplierName] NVARCHAR(1000) NOT NULL,
    [status] NVARCHAR(1000) NOT NULL,
    CONSTRAINT [Evaluation_pkey] PRIMARY KEY CLUSTERED ([id])
);

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
